version: "1.0"
services:
  postgresdb:
    image: postgres:16-bullseye
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: gambinha
      POSTGRES_DB: run-store
    volumes:
      - postgresdb-data:/var/lib/postgresql/data

  backend:
    image: todo_backend:latest
    ports:
      - 4000:3000
    environment:
      - DATABASE_URL=postgresql://gambinha:1234@postgresdb:5432/run-app?schema=public
      - JWT_SECRET=secret
    restart: always

  frontend:
    image: todo_frontend:latest
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - API_URL=http://localhost:4000
    restart: always

volumes:
  postgresdb-data:
